# Generated by Django 3.1.7 on 2021-04-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='itemname',
            new_name='item_name',
        ),
    ]
